### ISSUE TITLE
Allow spells to handle their own break event

### ISSUE THREAD

**Issue by mkarneim** [wizards-of-lua/wizards-of-lua#119]
Sometimes a spell creates some world objects that should be removed when the spell is broken.
Since a spell doesn't know when it's broken, this is currently not possible.

A solution to this would be to deliver a new "SpellBreakEvent" to the spell. 
* If the spell has registered an event listener for this, the spell can do some cleanup - and must, after that, terminate itself.
* If the spell has no event listener registered for this, WoL would break the spell immediately.

**Comment by Adrodoc55** [comment]
Does the spell really have to terminate or should we make the `SpellBreakEvent` cancelable? We could make it so `/kill` always terminates the spell whereas `/wol spell break` calls the event listener. This would be kind of similar to how a GUI application doesn't have to terminate when you press the X button, but it always terminates when you kill it via task manager.
If we do it this way, I think `/kill` should not notify the event listener.

**Comment by mkarneim** [comment]
For simplicity I decided to *not* make the ```SpellBreakEvent``` cancelable since the ```SpellEntity``` is not *killable* (by using ```/kill```) anymore because it has been migrated to be a virtual entity. 


Further, the event can not be *collected* by the breaking spell but only be *intercepted* since it occurs just before the spell is broken, and won't be delivered (for collection) to a dead spell.

So in order to let the spell do something when its own break event occurs it must use the event interceptor API. This implies, of course, that the spell must be *fast* in doing its own clean-up, since it must not exceed the configured ```eventListenerLuaTicksLimit```.

For example, the following spell resets the block to its original state when it is broken:
```lua
function blocker()
  spell.name = 'blocker'
  local old = spell.block:copy()
  Events.on('SpellBreakEvent'):call(function(e) 
    spell.block = old
  end)
  
  local b = {Blocks.get('dirt'), Blocks.get('grass')}
  local count = 1
  while true do
    sleep(10)
    count = count + 1
    spell.block = b[count%2+1]
  end
end
```

**Comment by Adrodoc** [comment]
We could add `/wol spell kill ...` as a replacement for `/kill`.

**Comment by Adrodoc** [comment]
But I am fine with the current approach that sounds good too.

**Comment by mkarneim** [comment]
Thanks. Fixed.
