### ISSUE TITLE
Material.name contains incorrect name

### ISSUE THREAD

**Issue by mkarneim** [wizards-of-lua/wizards-of-lua#151]
The field ```Material.name``` contains an incorrect value.

For example, this is the output of ```/lua print(str(spell.block))``` when the player is looking at a grass block:
```lua
{
  data = {
    snowy = false
  },
  material = {
    blocksLight = true,
    blocksMovement = true,
    canBurn = false,
    liquid = false,
    mobility = "NORMAL",
    name = "field_151577_b",
    opaque = true,
    replaceable = false,
    requiresNoTool = true,
    solid = true
  },
  name = "grass",
  nbt = nil
}
```
As you can see, the "name" is "field_151577_b".

**Comment by mkarneim** [comment]
This is because Minecraft is obfuscated, which means that Java Reflection is not giving the correct names.

**Comment by Adrodoc55** [comment]
I think we could use a small annotation processor to extract the field names at compile time if we don't want to list the materials explicitly.
