### ISSUE TITLE
Links to edit suggested files don't work when running WoL on Windows

### ISSUE THREAD

**Issue by Adrodoc55** [wizards-of-lua/wizards-of-lua#164]
On Windows the file seperator is `\`. Because of this the paths suggested by tabcompletion of commands like `/wol file edit` contain `\`. A `\` is not allowed in an URL and so the URL that is printed in the chat is not clickable. We should either suggest paths containing `/` or replace all `\` before printing the URL in the chat.

**Comment by mkarneim** [comment]
@Adrodoc55 , may I ask you to test the supplied fix since I have no access to MS Windows?

**Comment by Adrodoc55** [comment]
@mkarneim I can confirm, that the bug is fixed on branch `fix/#164` (in 69fb380)
