### ISSUE TITLE
Change mod ID from "luamod" to "wol"

### ISSUE THREAD

**Issue by mkarneim** [wizards-of-lua/wizards-of-lua#19]
See above.

**Comment by Adrodoc55** [comment]
Maybe also change the `admin` command to `/wol` or should that be considered to be a seperate issue?

**Comment by mkarneim** [comment]
Thosu should go into a separate issue.

**Comment by Adrodoc55** [comment]
If the mod ID can contain hyphens then "wizards-of-lua" would be a way better option in my opinion. Even if hyphens are not an option I would prefer the camel case variant over "wol".

**Comment by mkarneim** [comment]
The mod ID has some effects on the code. For example the `SpellEntity` is registered as  "luamod.Spell" right now (you can use this in @e selectors).
The mod ID is used as a prefix for the entity name.
So I think it should be short.
Additionally the mod ID is not used prominently, so normal users won't notice it.

**Comment by Adrodoc55** [comment]
Can you not register the SpellEntity as "spell" to allow for a selection like `@e[type=spell]`? If the mod ID is a required prefix for selecting by type, then I am fine with the shorter "wol" (`@e[type=wol.spell]`).
Note that minecraft uses lower underscore for types, for instance `@e[type=armor_stand]`.

**Comment by mkarneim** [comment]
So "wol" is acknowledged.
