### ISSUE TITLE
Setting the value for Player.pos somehow resets the rotationYaw

### ISSUE THREAD

**Issue by mkarneim** [wizards-of-lua/wizards-of-lua#193]
The problem is that the players's rotation is somehow reseted to a previous value.
When I execute this code:
```lua
/lua for i=1,10 do 
  spell.owner.pos = spell.owner.pos+spell.owner.lookVec*2; 
  sleep(10);
end
```
and do look around by mouse, the vision is jumpy.

For comparison, the following code works just fine: 
```lua
/lua for i=1,10 do 
  p=spell.owner.pos+spell.owner.lookVec*2; 
  spell:execute("tp %s %s %s %s",spell.owner.name, p.x,p.y,p.z);
  sleep(10); 
end
```

**Comment by Adrodoc** [comment]
I can't reproduce this. I tried using a modded client (launched in debug mode) in single player and against a local server (also launched in debug mode) on 081d033 as well as a vanilla client against the red magic server on 1.12.2-2.1.0-SNAPSHOT.

**Comment by Adrodoc** [comment]
The only thing I can see that might be mistaken for a WOL bug is that you can get stuck in the ground which can cause a jumpy camera, but you can do that with both variants listed above if you look slightly downwards by executing `/tp ~ ~ ~ ~ 0.01` before executing the Lua command.
But then again you can achieve this effect by standing on the ground and executing: `/tp ~ ~-.001 ~`
