### ISSUE TITLE
Support NBT type: net.minecraft.nbt.NBTTagByteArray

### ISSUE THREAD

**Issue by mkarneim** [wizards-of-lua/wizards-of-lua#195]
I looked at a "chiseled" block (I combined [Chisels & Bits](https://minecraft.curseforge.com/projects/chisels-bits) with Wizards of Lua) and casted the following spell:
```lua
/lua print(str(spell.block))
```
But sadly I got the following error:
```
Error during spell execution: Unsupported NBT type for conversion: 
net.minecraft.nbt.NBTTagByteArray
at line 137 of wol.inspect
at line 338 of wol.inspect
at line 1 of command-line
```

**Comment by mkarneim** [comment]
I added the NbtByteArrayMerger. Don't know if this is correct.
@Adrodoc, please see branch https://github.com/wizards-of-lua/wizards-of-lua/tree/fix/195

**Comment by Adrodoc** [comment]
Opening a pull request is beneficial for reviews.
Regarding the NbtByteArrayMerger:
1. You give an incorrect error message for tables that are not arrays. Something along the lines of `Can't convert nbt.a.b! table expected, but got table`.
2. This `if`is unnecessary as it can never be `false`: `if (newLuaValue != null)`.
3. I think it is unreasonable to parse strings into a byte with `Conversions.integerValueOf(newLuaValue)` instead I would check if the value is `instanceof Number` and if not `throw converter.conversionException(path + '[' + (i + 1) + ']', data, "number")`.
4. Use `Ints.checkedCast(long)` on the length, it is shorter and noone will ever see that error message anyways.
5. Doesn't it make more sence to allow an incomplete data table? This way you could just change the byte at index 5.
6. We should also add NbtIntArrayMerger and NbtLongArrayMerger.

**Comment by Adrodoc** [comment]
Regarding the method `NbtMerger.toLua(NBTTagByteArray)`, we could unify this with `NbtMerger.toLua(NBTTagIntArray)`. Instead of 
```java

  public static Table toLua(NBTTagIntArray nbt) {
    checkNotNull(nbt, "nbt == null!");
    Table result = new DefaultTable();
    int[] arr = nbt.getIntArray();
    for (int i = 0; i < arr.length; ++i) {
      long key = i + 1;
      Object value = arr[i];
      result.rawset(key, value);
    }
    return result;
  }
  
  public static Table toLua(NBTTagByteArray nbt) {
    checkNotNull(nbt, "nbt == null!");
    Table result = new DefaultTable();
    byte[] arr = nbt.getByteArray();
    for (int i = 0; i < arr.length; ++i) {
      long key = i + 1;
      Object value = arr[i];
      result.rawset(key, value);
    }
    return result;
  }
```
We can do:
```java

  public static Table toLua(NBTTagIntArray nbt) {
    return toLua(Ints.asList(nbt.getIntArray()));
  }

  public static Table toLua(NBTTagByteArray nbt) {
    return toLua(Bytes.asList(nbt.getByteArray()));
  }

  private static Table toLua(Iterable<?> it) {
    Table result = new DefaultTable();
    int i = 0;
    for (Object value : it) {
      i++;
      result.rawset(i, value);
    }
    return result;
  }
```

**Comment by Adrodoc** [comment]
I think this is how I would do it:
```java
package net.wizardsoflua.lua.nbt;

import static com.google.common.base.Preconditions.checkNotNull;

import java.util.ArrayList;
import java.util.Map.Entry;

import com.google.common.primitives.Bytes;

import net.minecraft.nbt.NBTTagByteArray;
import net.sandius.rembulan.Table;
import net.wizardsoflua.config.ConversionException;
import net.wizardsoflua.lua.table.TableIterable;

/**
 * @author Adrodoc
 */
public class NbtByteArrayMerger implements NbtMerger<NBTTagByteArray> {
  private final NbtConverter converter;

  public NbtByteArrayMerger(NbtConverter converter) {
    this.converter = checkNotNull(converter, "converter == null!");
  }

  @Override
  public NBTTagByteArray merge(NBTTagByteArray nbt, Object data, String pathKey, String path) {
    if (data instanceof Table) {
      Table table = (Table) data;
      ArrayList<Byte> bytes = new ArrayList<>(Bytes.asList(nbt.getByteArray()));
      for (Entry<Object, Object> entry : new TableIterable(table)) {
        Object key = entry.getKey();
        if (!(key instanceof Number)) {
          throw new ConversionException("Can't convert " + path
              + "! The specified table contains a key that can't be converted to an integer: "
              + key);
        }
        int index = ((Number) key).intValue();

        Object value = entry.getValue();
        if (!(value instanceof Number)) {
          throw converter.conversionException(path, value, "number");
        }
        Byte element = ((Number) value).byteValue();

        bytes.ensureCapacity(index + 1);
        bytes.set(index, element);
      }
      byte[] array = Bytes.toArray(bytes);
      return new NBTTagByteArray(array);
    }
    throw converter.conversionException(path, data, "table");
  }
}
```

**Comment by Adrodoc** [comment]
Considering that we should add multiple array mergers here is an implementation with an abstract base class:
```java
package net.wizardsoflua.lua.nbt;

import static com.google.common.base.Preconditions.checkNotNull;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Map.Entry;

import com.google.common.primitives.Bytes;

import net.minecraft.nbt.NBTBase;
import net.minecraft.nbt.NBTTagByteArray;
import net.sandius.rembulan.Table;
import net.wizardsoflua.config.ConversionException;
import net.wizardsoflua.lua.table.TableIterable;

/**
 * @author Adrodoc
 */
public abstract class NbtArrayMerger<NBT extends NBTBase, E> implements NbtMerger<NBT> {
  protected final NbtConverter converter;

  public NbtArrayMerger(NbtConverter converter) {
    this.converter = checkNotNull(converter, "converter == null!");
  }

  @Override
  public NBT merge(NBT nbt, Object data, String pathKey, String path) {
    if (data instanceof Table) {
      Table table = (Table) data;
      ArrayList<E> list = new ArrayList<>(asList(nbt));
      for (Entry<Object, Object> entry : new TableIterable(table)) {
        int index = convertKey(entry.getKey(), path);
        E element = convertValue(entry.getValue(), path);
        list.ensureCapacity(index + 1);
        list.set(index, element);
      }
      return toNbt(list);
    }
    throw converter.conversionException(path, data, "table");
  }

  protected abstract Collection<? extends E> asList(NBT nbt);

  protected int convertKey(Object key, String path) {
    if (key instanceof Number) {
      return ((Number) key).intValue();
    }
    throw new ConversionException("Can't convert " + path
        + "! The specified table contains a key that can't be converted to an integer: " + key);
  }

  protected abstract E convertValue(Object value, String path);

  protected abstract NBT toNbt(List<E> list);
}


/**
 * @author Adrodoc
 */
class NbtByteArrayMerger extends NbtArrayMerger<NBTTagByteArray, Byte> {
  public NbtByteArrayMerger(NbtConverter converter) {
    super(converter);
  }

  @Override
  protected Collection<? extends Byte> asList(NBTTagByteArray nbt) {
    return Bytes.asList(nbt.getByteArray());
  }

  @Override
  protected Byte convertValue(Object value, String path) {
    if (value instanceof Number) {
      return ((Number) value).byteValue();
    }
    throw converter.conversionException(path, value, "number");
  }

  @Override
  protected NBTTagByteArray toNbt(List<Byte> list) {
    byte[] array = Bytes.toArray(list);
    return new NBTTagByteArray(array);
  }
}
```

**Comment by Adrodoc** [comment]
Using my implementations you can't reduce the size of an arrow, but this is a fundamental problem with the ambiguity of the merge operation. [With nbt lists we act differently depending on the name of the tag](https://github.com/wizards-of-lua/wizards-of-lua/blob/fix/195/src/main/java/net/wizardsoflua/lua/nbt/NbtListMerger.java#L46-L50), for AttributeModifiers and scoreboard tags we replace the list and for others we actually merge the lists. This was done to mimic Minecraft's behaviour of the `entitydata` command, but it seems like there are no entities that make use of arrays, so we can't mimic Minecraft here.
Maybe we need to do it similar to what they did in 1.13 with the new [data command](https://minecraft.gamepedia.com/Commands/data) and add a remove function to get rid of nbt values. But then we hit the issue of not knowing the type of nbt to put there if we removed the original value. Maybe we should allow a magic key like `__nbttype`?

**Comment by mkarneim** [comment]
Thank you for all your considerations!

The ambiguity problem was the reason I posted this question in the first place.

By now I guess the "merging" style (which means to apply new or changed values, but not to remove "missing" ones) makes sense to be used when the target structure is *not* array-like but instead some key-value structure. Hence, the "overwrite" style (which means that old values are just dropped and the new ones are inserted) should be applied to array-like structures. 

Since NBTTagByteArray is an array, the NbtByteArrayMerger should create a new NBTTagByteArray with the values from the Lua table and just ignore the values of the old NBTTagByteArray in the target object completely.

This actually makes sense in the context of the "chiseled block", which is a block having a NBTTagByteArray with the key "X" in its NBT section. This property describes in an "encoded" way the substructure of the block. When writing new data into "X" you really want to replace the whole array with the new one (see "overwrite" style) - especially since "merging" will just produce data garbage (and the block will disappear). 

So, when I understand it correctly, your code supports this behavior, doesn't it?

**Comment by mkarneim** [comment]
Further, for cases where the "standard" behavior isn't suitable, we should support some API that allows the user to control this better. I guess, a function for "removing" a value for a specific key is a good start.

Also, your suggestion for some "magic" key (```__nbttype```) sounds reasonable.

**Comment by mkarneim** [comment]
Perhaps we should support two distinct methods for this?

The "default" behavior (merging structures, overwriting arrays) would be used by calling ```putNbt```, for example:
```lua
entity:putNbt({someKey=someValue})
```

If the user needs total control, the ```setNbt``` function could be used:
```lua
entity:setNbt({someKey=someValue})
```
This would replace the object's NBT with the specified one.

**Comment by Adrodoc** [comment]
You misunderstood, my code does not support your proposed behaviour, instead it merges arrays.

I am not a big fan of merging compounds but replacing arrays, what if the user wants to merge arrays. The cleanest way to avoid ambiguity may actually be to not support merging at all and require the user to get modify and set the nbt value. This is of course more complicated in Lua and may be a bad idea when autosleep is enabled, but we could get rid of all nbt mergers and the different list merge strategies that are used based on the nbt name. If we go for this option we should seriously reconsider #30 as it deals with both the more complex Lua code and the autosleep issue.

**Comment by Adrodoc** [comment]
Regarding #30 I would use the third option listed there (detachable nbt backed tables) and additionally allow tables to specify the nbt type:
```lua
spell.owner.nbt.dimension = {__nbttype = "int", value = 2}
spell.owner.nbt.dimension = 1
spell.owner.nbt.Motion = {__nbttype = "double_list", value = {0, 5, 0}}
spell.owner.nbt.Motion = {0, 5, 0}
spell.owner.nbt.Motion = {2 = 5}
```
For the nbttype we probably need to differentiate between `int_array` and `int_list` thus I used `double_list` in the example and not just `double` even though that wouldn't be ambiguous either.

**Comment by mkarneim** [comment]
Ah, I didn't get this part, where the "old" values are copied: 
```java
ArrayList<E> list = new ArrayList<>(asList(nbt));
```
If we change this to 
```java
ArrayList<E> list = new ArrayList<>();
```
then we have it the way I suggested.

**Comment by mkarneim** [comment]
> I am not a big fan of merging compounds but replacing arrays, what if the user wants to merge arrays? 

This involves a little bit more work on the user's side. He still can achieve this by "copying" the original array, then modifying it, and finally putting it back to the nbt.

For example:
```lua
array = entity.nbt.a.b.c -- e.g. {1,2,3,4}
array[1]=5
array[2]=6
entity:putNbt({a={b={c=array}}})
```
This would produce {5,6,3,4} at node a.b.c.

But I understand you concerns. It's just that there are multiple options to solve this and I like to check all of them.

Handling arrays differently is a bit like treating them like an extra kind of value type, as though they had nothing to do with the table type. Tables are "merged", and numbers, strings, booleans, and arrays are "replaced".

For example, if you write it like this:
```lua
entity:putNbt({a={b={c={0,8,15}}}})
```
it looks very similar to this:
```lua
entity:putNbt({a={b={c=7}}})
```
Nobody would misunderstand it, I think.

**Comment by Adrodoc** [comment]
You are right, ommiting the initial copy of old values changes it according to your proposed behaviour.

Yes I know that you can always achieve what you want with get, modify and set. My point was more about: I don't like it that tables that represent arrays are handled differently that tables that represent compounds. I also don't like that tables that represent lists are sometimes handled like arrays and sometimes like compounds.

What do you think about my proposal to remove support for merging nbt altogether in favour of #30?

**Comment by mkarneim** [comment]
I am not sure. How would you address the [problem you mentioned](https://github.com/wizards-of-lua/wizards-of-lua/issues/30#issuecomment-299959103)?

**Comment by Adrodoc** [comment]
I would say that you can detach an nbt based table in which case it stops delegating changes (the third option proposed in #30). I am not entirely sure on whether I would allow using a detached table or whether it should throw an exception when someone tries to read/modify a detached table. Both would work. If we allow using a detached table we would need to copy the appropriate data when detaching to keep a "snapshot" for later access.
In either case we should make a class for each nbt type so you can tell that it is not a normal table in Lua and we should add a function `isDetached` or `isAttached`.

**Comment by Adrodoc** [comment]
Unfortunately I don't know the future either :P

**Comment by mkarneim** [comment]
Ah damn!
I just thought I could blag some promises  ;-)

**Comment by Adrodoc** [comment]
If a detached nbt table is still usable you can in theory get strange behaviour with autosleep.
For instance this code:
```lua
spell.owner.nbt.a.b = 123
```
may or may not do anything, because a different spell could detach `a` immediately before `b` is set if this spell falls asleep after retrieving `a`.
I highly doubt this will ever occur in practice, but it is an argument against usable detached nbt tables.
