### ISSUE TITLE
Rename Repository to wizards-of-lua?

### ISSUE THREAD

**Issue by Adrodoc55** [wizards-of-lua/wizards-of-lua#22]
Because luamod does not sound nearly as fancy. That way the repository would have that same name as the organization, I don't know if that would be a problem.

**Comment by mkarneim** [comment]
Yes, since we plan to call the mod "Wizards of Lua", weh should also call the repo like that.
"wol" is another possible name.
Comments?

**Comment by Adrodoc55** [comment]
I would not call the repository​ wol, but I really like the name wizards-of-lua​ for the repository​

**Comment by mkarneim** [comment]
Done.
