### ISSUE TITLE
Entities.find() doesn't work for exact names or uuids

### ISSUE THREAD

**Issue by ShadowFoxNixill** [wizards-of-lua/wizards-of-lua#240]
Example: `Entities.find("ShadowFoxNixill")` and `Entities.find("cb983604-f413-4880-b21e-36fe5d6e186a")` both return `{}` even when I'm online. They should return a reference to me.

**Comment by Adrodoc** [comment]
In 1.13 we have this behaviour anyways and it would be quite difficult to simulate the current behaviour.
Since `Entities.find` is supposed to behave like selectors in commands, I consider this to be a bug.
