### ISSUE TITLE
[1.13.2] /wol file edit doesn't work with folders

### ISSUE THREAD

**Issue by mkarneim** [wizards-of-lua/wizards-of-lua#248]
For example `/wol file edit abc/xyz.lua` can't be submitted, since the command parser says: "Expected whitespace to end one argument, but found tailing data".

Same it true for `/wol shared-file edit`

**Comment by mkarneim** [comment]
Fixed in branch mc-1.13-rebased

**Comment by Adrodoc** [comment]
The fix in `FileMoveCommand` does not work for paths containing spaces. How about we revert the fix for this class only and instruct users to quote their paths?

**Comment by mkarneim** [comment]
I know that quoting the path is possible. This fix here is just an alternative to it I wanted to try.

In the end I don’t like both of them. Both solutions are considerably worse than how this command was implemented in MC 1.12.2. I feel that we have to redesign this completely, especially to get back the autocompletion.
I am thinking about removing the “wol file” and “wol shared-file” commands and instead making a new command (something like “wol editor” or “wol browser open”) that just opens the browser showing some kind of file chooser or some text field with autocompletion implemented with java script.
This text field could also be added to every editor page to make it easier to open another file.
“Move” and “Delete” could be implemented as buttons.

**Comment by Adrodoc** [comment]
I prefer a filetree over a text field. Move could be implemented using drag and drop, to delete you could just press the delete key or right click to open a context menu. A search field is of course nice, but not absolutely necessary.

**Comment by Adrodoc** [comment]
Should we reopen this then?
