### ISSUE TITLE
Should registering for events really require the full LuaClass name?

### ISSUE THREAD

**Issue by Adrodoc55** [wizards-of-lua/wizards-of-lua#27]
Currently you have to specify the full LuaClass name in order to register yourself for events:
```lua
q = Events.register('ChatEvent', 'LeftClickBlockEvent')
```
I am still uncertain if this is really better than omitting the "Event" suffix. Without the suffix it is a lot shorter:
```lua
q = Events.register('Chat', 'LeftClickBlock')
```
This change would be very easy to implement, just remove the "Event" suffix from the module name in [ModEventHandler](https://github.com/wizards-of-lua/wizards-of-lua/blob/6dc0a5c0bad4a0bb861f7bbe0ad3bb970b7f6fe5/src/main/java/net/karneim/luamod/lua/event/ModEventHandler.java#L188). No change would be required for [custom events](https://github.com/wizards-of-lua/wizards-of-lua/blob/6dc0a5c0bad4a0bb861f7bbe0ad3bb970b7f6fe5/src/main/java/net/karneim/luamod/lua/event/Events.java#L83).

**Comment by mkarneim** [comment]
Users can always invent their own constants with shorter names if they need it.
