### ISSUE TITLE
Add Blocks.get(vec3/x, y, z) -> BlockState

### ISSUE THREAD

**Issue by Adrodoc55** [wizards-of-lua/wizards-of-lua#28]
Similar to `Blocks.getNbt`. Currently the only way to get a BlockState is `spell.block`...
Maybe we should add a Block class that contains a blockPos and the world and allows for object orientation:
```lua
b = Blocks.get(x, y, z)
print(b:getNbt())
print(b.pos)
print(b.material.isLiquid)
print(b.name)
```

**Comment by mkarneim** [comment]
Alright!
