### ISSUE TITLE
Automatically generate Lua documentation

### ISSUE THREAD

**Issue by mkarneim** [wizards-of-lua/wizards-of-lua#31]
In order to make it easier to update the Lua module documentation on the webpage, we need something that helps with that.
* extract the documentation from the java wrapper classes
* create some file with these contents so that it can be read by jekyll
* import this file manually into the webpage

**Comment by Adrodoc55** [comment]
I added this to the beta milestone, because the webpage should contain documentation for all versions of Wizards of Lua before we release WoL. This requirement is most likely going to be fixed with this issue.

**Comment by mkarneim** [comment]
Why is this still open although it is already fixed in #131.

**Comment by Adrodoc55** [comment]
Because this ticket includes integration of the webpage

**Comment by Adrodoc** [comment]
This is fixed as of b25959d.
