### ISSUE TITLE
Spell rotation should be aligned to command block

### ISSUE THREAD

**Issue by mkarneim** [wizards-of-lua/wizards-of-lua#4]
When a spell is casted by a command block, the spell's rotation currently is always aligned to absolute South.
I think it is better if the spell's rotation is aligned with the command block's facing.

**Comment by Adrodoc55** [comment]
What would be the appropriate ry-rotation when the command block is facing upwards/downwards? South?

**Comment by mkarneim** [comment]
Yes, I think "south" is a good choice since it has the rotation value 0.

**Comment by mkarneim** [comment]
Already fixed some time before. I just forgot to close this issue.
