### ISSUE TITLE
Wizards should be able to list their own active spells

### ISSUE THREAD

**Issue by mkarneim** [wizards-of-lua/wizards-of-lua#44]
This is an extension to the `/wol spell list all` action.

For example it could work like this:

- `/wol spell list mickkay` lists all active spells belonging to user mickkay.
- `/wol spell list` defaults to `/wol spell list <current user>`

**Comment by Adrodoc55** [comment]
I suggest using a syntax similar to #45: `/lua spell list byName Adrodoc55`

**Comment by mkarneim** [comment]
So I guess we'll do it like this:
* ```/wol spell list byOnwer mickkay``` lists all spells casted by mickkay.
* ```/wol spell list byName magicwand``` lists all spells with the name "magicwand".
