### ISSUE TITLE
Wizards should be able to define event handlers that cast spells automatically

### ISSUE THREAD

**Issue by mkarneim** [wizards-of-lua/wizards-of-lua#46]
This could be done with a new action of the `/wol` command or with a completely new command, e.g. `/event`.

For example:
- `/wol event add PlayerLoggedInEvent spell:say("Hello "..event.player.name.."!")

Also we need some control over listing and deleting event handlers.

For example:
- `/wol event list` would list all registered event handlers
- `/wol event list PlayerLoggedInEvent ` would list all registered event handlers for the PlayerLoggedInEvent
- `/wol event clear` would clear all registered event handlers
- `/wol event clear PlayerLoggedInEvent ` would clear all registered event handlers for the PlayerLoggedInEvent
- `/wol event remove PlayerLoggedInEvent 1` would remove the first of all event handlers for the PlayerLoggedInEvent

**Comment by Adrodoc55** [comment]
Why add a new command instead of a Lua module?
```lua
Events.register('PlayerLoggedInEvent', 'BlockBreakEvent', function(event)
  spell:say("Hello "..event.player.name.."!")
end);
```
Or as a fluent API:
```lua
Events.on('PlayerLoggedInEvent', 'BlockBreakEvent'):run(function(event)
  spell:say("Hello "..event.player.name.."!")
end);
```

**Comment by mkarneim** [comment]
Yes, this is a good idea, only that I guess we can't really pass a function reference there but instead should pass a string with the relevant code, e.g.:

```lua
Events.on('PlayerLoggedInEvent', 'BlockBreakEvent'):execute('spell:say("Hello "..event.player.name.."!")');
```

The reason for not passing a (compiled) function reference is, that we would need to store the generated byte code instead of the source code. This would break the reloading-feature (aka "cache clear") when updating the code.

**Comment by Adrodoc55** [comment]
Why would it break "cache clear"? I thought running spells are not affected by that.

**Comment by mkarneim** [comment]
We already have (actually we have it in the prototype) an API for event handling for running spells.
Running spells should not be affected by code reloading.

But this API here is an alternative to that.

With this API I want to support the configuration of event handlers that survive a server restart.
In the prototype we have something like this already implemented by 
```wol startup set <some lua code>```
which actually executes the given Lua code at server startup.

Using the new API this could be rewritten like this:
```lua
Events.on('ServerStart'):execute('....');
```

**Comment by Adrodoc55** [comment]
Does this mean that the final decision regarding spell persistence was that spells are never persisted? I can't remember. If you would support spell persistence for instance via a flag on the spell instance, then using a function would be possible, but that would require you to serialize the state of the lua program, which might be difficult.
Even with the string variant I think a Lua API is sufficient, but you should be able to tell from the name that these listeners are persistent.

**Comment by Adrodoc55** [comment]
One issue I can see with the lua API is that it seems like breaking the spell would remove the listener, which is of course not what happens.

**Comment by mkarneim** [comment]
OK, so maybe we rethink this completely.
The feature I want to have is, that after a server restart certain spells are automatically started (again), since we so not support spell persistence right now and possibly never.
It would be nice if every wizard could define his or her own "startup" spell. 
So I guess the old (say prototype) option (using /wol startup set <...>) was already good, except that it was globally defined. We just have to support a user-specific startup spells.
All other (non startup) events could be handled by the startup spell in the standard way.

**Comment by Adrodoc55** [comment]
Using a command like `/wol event add` makes it difficult to support multiple event types unless you use something like a comma separated list: `/wol event on PlayerLoggedInEvent,ServerStartEvent spell:say('Hello')

**Comment by mkarneim** [comment]
I suggest we implement it like this:
```lua
/wol startup mickkay set mystartupfunction() 
```

**Comment by Adrodoc55** [comment]
Should this also be THE way to receive cancelable events?

**Comment by mkarneim** [comment]
That was my original intension.
But I think we can split these two requirements.
Let's create a new issue for "cancelable" events.

**Comment by Adrodoc55** [comment]
I think it is also quite important to be able to remove specific event handlers for specific players

**Comment by mkarneim** [comment]
OK, I split this issue into two new issues:
* https://github.com/wizards-of-lua/wizards-of-lua/issues/56 - Support cancelable events
* https://github.com/wizards-of-lua/wizards-of-lua/issues/57 - Support user-specific startup spells
and will close this now.

**Comment by Adrodoc55** [comment]
Something to keep in mind is that if event handles use strings and start a new spell on every event, they will always be affected by code changes, unlike event handlers that use queues.
