### ISSUE TITLE
Add permissions required for casting a spell

### ISSUE THREAD

**Issue by mkarneim** [wizards-of-lua/wizards-of-lua#47]
This makes sense when server owners like to give their players the ability to cast spells without the necessity to give them operator privileges.

For example:
- Permission can be granted to players by name.
- Permission can be granted to players by game mode.
- Permission can be granted to players by role (player vs. operator).

Important: the player's permission must be propagated to the spell since it could execute a Minecraft command.

**Comment by Adrodoc55** [comment]
Related to #25

**Comment by mkarneim** [comment]
For now I just implement permissions by game mode.

**Comment by mkarneim** [comment]
I am closing this issue as "wontfix" since there is no straight way to do this right.
Actually you can't restrict a wizard effectively from doing harm on a server without restricting operators also. In the end you have to trust your operators, and this is true for wizards also.

However, I pushed my changes regarding this feature to [mickkay/permissions](https://github.com/wizards-of-lua/wizards-of-lua/tree/mickkay/permissions).
If somebody has a good idea about this, we could reactivate it.
