### ISSUE TITLE
Make a "Creature" class for all creature entities

### ISSUE THREAD

**Issue by mkarneim** [wizards-of-lua/wizards-of-lua#53]
The new "Creature" class should be a subclass of "Entity" and always be used for entity objects that are actually creatures.

The Creature entity should have an "ai" property that could be switched on and off.

**Comment by Adrodoc55** [comment]
Why are you not using the Minecraft classname (EntityLiving)? That would make it easier for wizards with forge experience and for the development of wol itself.

**Comment by mkarneim** [comment]
Because I guess that "EntityLiving" is not really the real classname but just the name that was chosen by the folks who decompiled Minecraft the first time. I think "Creature" is a more natural name.
Additionally I think we should not try do duplicate the Entity class hierarchy, since this could change in the future and then break our Lua API. While mods are required to be refactored and recompiled when there are substantial changes in the internal Minecraft classes, I hope we can get rid of this by just supporting a very simple and hopefully very stable class hierarchy.
However, I think we could and should add a Lua class for every concrete entity class like "Pig", "Wolf", and "Creeper", which should extend just "Creature".
