### ISSUE TITLE
Direct LUA actions for buttons/levers/etc.

### ISSUE THREAD

**Issue by bytemage** [wizards-of-lua/wizards-of-lua#7]
Currently a command block is needed to execute LUA on a button press or similar actions.
It would be nice to have an event to register in LUA to get those.
Or extending the onClick functionality some blocks already possess.

**Comment by mkarneim** [comment]
This is a question for @Adrodoc55: is there something like an event for pressing buttons in Forge/MC?

**Comment by Adrodoc55** [comment]
For ingame levers and buttons I would use the event `RIGHT_CLICK` which is actually the event `net.minecraftforge.event.entity.player.PlayerInteractEvent.RightClickBlock` (maybe wenn should rename that to RIGHT_CLICK_BLOCK). Unfortunately this event does not have it's own lua-subclass and instead uses an instance of [PlayerInteractEventClass](https://github.com/wizards-of-lua/luamod/blob/master/src/main/java/net/karneim/luamod/lua/event/PlayerInteractEventWrapper.java).
Maybe wenn should get rid of the enum [EventType](https://github.com/wizards-of-lua/luamod/blob/master/src/main/java/net/karneim/luamod/lua/event/EventType.java) and instead use the name of the lua-class (without suffix) directly, for instance: ```lua
local q = Events.register(AnimationHand)
```
In this case I'd rename [AnimationHandEventClass](https://github.com/wizards-of-lua/luamod/blob/master/src/main/java/net/karneim/luamod/lua/classes/event/AnimationHandEventClass.java) to AnimationHand.
For detecting the press of a keyboard button, we would have to intercept the appropriate client packet, similar to what we do for ANIMATION_HAND and CLICK_WINDOW in [ModEventHandler](https://github.com/wizards-of-lua/luamod/blob/master/src/main/java/net/karneim/luamod/lua/event/ModEventHandler.java#L47-L65).

**Comment by mkarneim** [comment]
Using the event's classname will not work for custom events (currently bad named instances of GenericEvent).

Besides that using the event's classname would be OK for me.
If events have a deep inheritance hierarchy I guess we then could also register to some event with subclasses and receive all of the subclass events?

**Comment by Adrodoc55** [comment]
@bytemage Is this question answered sufficiently? Then we could close this issue.

**Comment by Adrodoc55** [comment]
Closed due to inactivity.
