### ISSUE TITLE
Support the dynamic creation of custom commands

### ISSUE THREAD

**Issue by mkarneim** [wizards-of-lua/wizards-of-lua#76]
For example
```
/wol command set hello require("foo"); bar(command)
```
will add a new command to the server called "hello".

When a player types
```
/hello arg1 arg2
```
then a new spell is casted that executes the following source code:
```lua
require("foo"); bar(command)
```

The command variable will look like this:
```
{ name="hello", 
  args={"arg1","arg2"},
  sender=<command sender>
}
```
where ```<command sender>``` will be replaced by the respective Player instance.

To delete a command, just use:
```
/wol command unset hello
```

To print a command, use:
```
/wol command get hello
```

**Comment by handicraftsman** [comment]
```lua
add_command('ping', function(event)
  event:reply('Pong!')
  event:reply(event.args[1])
end
```

**Comment by Adrodoc55** [comment]
Is this still neccessary? As of #56 you can cancel `ChatEvent`s. This allows you to create custom commands as long as they don't start with a `/`.
Here is a "command" that turns the block you are looking at into a gold block when you type `:gold` in the chat:
```lua
function registerGoldCommand()
  Events.on('ChatEvent'):call(function(event)
    if event.message == ':gold' then
      event.canceled = true
      local player = event.player
      local hit = player:scanView(5)
      if hit ~= nil then
        spell.pos = hit.pos
        spell.block = Blocks.get('gold_block')
      else
        spell:execute('tellraw %s {"text":"look at a block to use this command","color":"red"}', player.name)
      end
    end
  end)
end
```

**Comment by mkarneim** [comment]
Well, it is not necessary, but it would be neat.

Maybe we could implement by using the CommandEvent.
